server:
  port: 9000

spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri:
            http://localhost:8082
          predicates:
            - Path=/kin-mel/product-service/**

        - id: TRANSACTION
          uri:
            http://localhost:8083
          predicates:
            - Path=/kin-mel/pay-service/pay
            - Method=POST

